CREATE TABLE IF NOT EXISTS auditoria (
    id INT AUTO_INCREMENT NOT NULL,
    tabla VARCHAR(100) NOT NULL,
    operacion VARCHAR(100) NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    fecha TIMESTAMP NOT NULL,   --EN EL SELECT SE SEPARARÁN FECHA Y HORA
    CONSTRAINT pk_auditoria PRIMARY KEY (id)

);
